[package]
name = "uwb_delay_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dt_delay_test"
path = "src/dt_delay_test.rs"

[[bin]]
name = "dt_bidi_test"
path = "src/dt_bidi_test.rs"

[[bin]]
name = "master"
path = "src/bin/master.rs"

[[bin]]
name = "slave"
path = "src/bin/slave.rs"

[dependencies]
serialport = "4.5"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
crossterm = "0.27"
ctrlc = "3.4"

[profile.release]
opt-level = 3
lto = true
